In [33]:
import numpy as np
import sympy
from math import factorial

In [38]:
A_L = np.array([[1, 0, 0, 1], [1, 1, 0, 1], [0, 0, 1, 0], [0, 0, 1, 1]])
print A_L
A_R = np.array([[1,0,1,1,],[0,1,0,1],[0,0,1,0],[0,0,0,1]])
A_R_sym = sympy.Matrix(A_R)

[[1 0 0 1]
 [1 1 0 1]
 [0 0 1 0]
 [0 0 1 1]]


In [13]:
a = np.array([[1,2],[3,4]])
m = sympy.Matrix(A_L)

In [14]:
P, J = m.jordan_form()
J

Matrix([
[1, 1, 0, 0],
[0, 1, 1, 0],
[0, 0, 1, 1],
[0, 0, 0, 1]])

In [32]:
np.linalg.matrix_power(J,10)

array([[1, 10, 45, 120],
       [0, 1, 10, 45],
       [0, 0, 1, 10],
       [0, 0, 0, 1]], dtype=object)

In [35]:
def nCr(n,r):
    val = factorial(n)/(factorial(n-r)*factorial(r))
    return val

In [39]:
P, J = A_R_sym.jordan_form()
J

Matrix([
[1, 1, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 1],
[0, 0, 0, 1]])