In [29]:
import numpy as np
import tabulate

# Problem 10.1

## 10.1(a)

In [28]:
# form minimal state space realization
N = 3
A = np.array([[1,0,0],[0,2,0],[0,0,1]])
B = np.array([[1,0],[1,1],[0,1]])
C = np.array([[1,1,0],[0,1,1]])


# controllability matrix
T_ctrl = np.hstack((B, np.dot(A,B), np.dot(A,np.dot(A,B))))
T_obs = np.vstack((C,np.dot(C,A),np.dot(C,np.dot(A,A))))

np.shape(T_ctrl)
print " shape T_obs = ", np.shape(T_obs)
ctrl_rank = np.linalg.matrix_rank(T_ctrl)
obs_rank = np.linalg.matrix_rank(T_obs)

print "ctrl_rank = ", ctrl_rank
print "obs_rank = ", obs_rank

 shape T_obs =  (6, 3)
ctrl_rank =  3
obs_rank =  3


In [36]:
print tabulate.tabulate(A, tablefmt='latex')
print tabulate.tabulate(B, tablefmt='latex')
print tabulate.tabulate(C, tablefmt='latex')
print tabulate.tabulate(T_ctrl, tablefmt='latex')
print tabulate.tabulate(T_obs, tablefmt='latex')

\begin{tabular}{rrr}
\hline
 1 & 0 & 0 \\
 0 & 2 & 0 \\
 0 & 0 & 1 \\
\hline
\end{tabular}
\begin{tabular}{rr}
\hline
 1 & 0 \\
 1 & 1 \\
 0 & 1 \\
\hline
\end{tabular}
\begin{tabular}{rrr}
\hline
 1 & 1 & 0 \\
 0 & 1 & 1 \\
\hline
\end{tabular}
\begin{tabular}{rrrrrr}
\hline
 1 & 0 & 1 & 0 & 1 & 0 \\
 1 & 1 & 2 & 2 & 4 & 4 \\
 0 & 1 & 0 & 1 & 0 & 1 \\
\hline
\end{tabular}
\begin{tabular}{rrr}
\hline
 1 & 1 & 0 \\
 0 & 1 & 1 \\
 1 & 2 & 0 \\
 0 & 2 & 1 \\
 1 & 4 & 0 \\
 0 & 4 & 1 \\
\hline
\end{tabular}


In [63]:
B_pinv = np.linalg.inv(np.dot(B.transpose(),B))
D = np.diag([-2,-3,-2])

F = np.dot(B_pinv, np.dot(B.transpose(), D))
print D
print B_pinv
print F

[[-2  0  0]
 [ 0 -3  0]
 [ 0  0 -2]]
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[-1.33333333 -1.          0.66666667]
 [ 0.66666667 -1.         -1.33333333]]


In [74]:
B_pinv = np.linalg.pinv(B)
F = np.dot(B_pinv, D)
test = A + np.dot(B,F)
print test

test2 = np.dot(B_pinv, B)
print B_pinv

[[-0.33333333 -1.          0.66666667]
 [-0.66666667  0.         -0.66666667]
 [ 0.66666667 -1.         -0.33333333]]
[[ 0.66666667  0.33333333 -0.33333333]
 [-0.33333333  0.33333333  0.66666667]]
