In [8]:
import numpy as np
import tabulate
import scipy
import scipy.signal

# Problem 10.1

## 10.1(a)

In [19]:
# form minimal state space realization
N = 3
A = np.array([[1,0,0],[0,2,0],[0,0,1]])
B = np.array([[1,0],[1,1],[0,1]])
C = np.array([[1,1,0],[0,1,1]])
C_2 = -C

# controllability matrix
T_ctrl = np.hstack((B, np.dot(A,B), np.dot(A,np.dot(A,B))))
T_obs = np.vstack((C,np.dot(C,A),np.dot(C,np.dot(A,A))))

np.shape(T_ctrl)
print " shape T_obs = ", np.shape(T_obs)
ctrl_rank = np.linalg.matrix_rank(T_ctrl)
obs_rank = np.linalg.matrix_rank(T_obs)

print "ctrl_rank = ", ctrl_rank
print "obs_rank = ", obs_rank

 shape T_obs =  (6, 3)
ctrl_rank =  3
obs_rank =  3


In [21]:
eps = 1e-5
poles = np.array([-1,-(1 + eps),-(1 + 2*eps)])
full_state_feedback = scipy.signal.place_poles(A,B,poles)
F = full_state_feedback.gain_matrix
print(full_state_feedback.computed_poles)
print("F = \n", F)

observer = scipy.signal.place_poles(A.transpose(), C_2.transpose(), poles)
L = -observer.gain_matrix
L = L.transpose()
print(L)

[-1.00002    -1.00001    -1.00000765]
('F = \n', array([[-1.00613049,  4.50920321, -3.00614049],
       [-2.99392481,  4.49087974, -0.99391481]]))
[[-1.00613049 -2.99392481]
 [ 4.50920321  4.49087974]
 [-3.00614049 -0.99391481]]


In [3]:
print tabulate.tabulate(A, tablefmt='latex')
print tabulate.tabulate(B, tablefmt='latex')
print tabulate.tabulate(C, tablefmt='latex')
print tabulate.tabulate(T_ctrl, tablefmt='latex')
print tabulate.tabulate(T_obs, tablefmt='latex')

\begin{tabular}{rrr}
\hline
 1 & 0 & 0 \\
 0 & 2 & 0 \\
 0 & 0 & 1 \\
\hline
\end{tabular}
\begin{tabular}{rr}
\hline
 1 & 0 \\
 1 & 1 \\
 0 & 1 \\
\hline
\end{tabular}
\begin{tabular}{rrr}
\hline
 1 & 1 & 0 \\
 0 & 1 & 1 \\
\hline
\end{tabular}
\begin{tabular}{rrrrrr}
\hline
 1 & 0 & 1 & 0 & 1 & 0 \\
 1 & 1 & 2 & 2 & 4 & 4 \\
 0 & 1 & 0 & 1 & 0 & 1 \\
\hline
\end{tabular}
\begin{tabular}{rrr}
\hline
 1 & 1 & 0 \\
 0 & 1 & 1 \\
 1 & 2 & 0 \\
 0 & 2 & 1 \\
 1 & 4 & 0 \\
 0 & 4 & 1 \\
\hline
\end{tabular}


In [6]:
print(C)

[[1 1 0]
 [0 1 1]]
